<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>
  <ItemGroup>
    <Watch Include="**/*.val" />
    <Src Condition=" '$(VALFiles)' == ''" Include="**/*.val" />
    <Src Condition=" '$(VALFiles)' != ''" Include="$(VALFiles)/**/*.val" />
  </ItemGroup>
  <Target
    Name="generate-parse"
    BeforeTargets="BeforeBuild"
    Inputs="@(Src)"
    Outputs="out/parsers.fs"
  >
    <MakeDir Directories="out" />
    <Exec Command="dotnet fsi generate-parse.fsx &quot;@(Src,';')&quot; > out/generate-parse.out.txt" />
  </Target>
  <ItemGroup>
    <Compile Include="out/parsers.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FParsec" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="FSharp.Data" />
  </ItemGroup>
</Project>
